import { MessageParticipantRole } from 'twenty-shared/types';

import { MessageDirection } from 'src/modules/messaging/common/enums/message-direction.enum';
import { type MessageWithParticipants } from 'src/modules/messaging/message-import-manager/types/message';
import { filterOutUnsubscribeRequests } from 'src/modules/messaging/message-import-manager/utils/filter-out-unsubscribe-requests.util';

const OWN_HANDLES = ['user@example.com'];

const buildMessage = (
  externalId: string,
  participants: MessageWithParticipants['participants'],
  direction: MessageDirection = MessageDirection.OUTGOING,
): MessageWithParticipants => ({
  externalId,
  subject: 'unsubscribe',
  receivedAt: new Date('2025-09-23T08:28:18.000Z'),
  text: 'This message was automatically generated by Gmail.',
  headerMessageId: `<${externalId}@mail.gmail.com>`,
  messageThreadExternalId: `thread-${externalId}`,
  direction,
  participants,
  attachments: [],
  isDraft: false,
});

describe('filterOutUnsubscribeRequests', () => {
  it('should filter out the request the mail client sends on the user behalf when clicking unsubscribe', () => {
    const messages = [
      buildMessage('gmail-unsubscribe', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'user@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle:
            '32.MRTVISTNM5XUEQKONZGTO6K7LF5E6ODWIFNGY6STG53FGMKBGVXDMU3TGZGHAUJSN5IT2PI=@unsubscribe2.customer.io',
          displayName: '',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual([]);
  });

  it('should filter out the confirmation the unsubscribe mailbox sends back', () => {
    const messages = [
      buildMessage(
        'unsubscribe-confirmation',
        [
          {
            role: MessageParticipantRole.FROM,
            handle: 'unsubscribe@mail.vendor.com',
            displayName: 'Vendor',
          },
          {
            role: MessageParticipantRole.TO,
            handle: 'user@example.com',
            displayName: 'User',
          },
        ],
        MessageDirection.INCOMING,
      ),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual([]);
  });

  it('should filter out the RFC 2369 unsubscribe command sent to a neutral list address', () => {
    const messages = [
      buildMessage('list-command', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'user@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle: 'list@host.com',
          displayName: '',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual([]);
  });

  it('should filter out the unsubscribe command even when the client adds a reply-to participant', () => {
    const messages = [
      buildMessage('list-command-with-reply-to', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'user@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.REPLY_TO,
          handle: 'user.alias@personal.org',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle: 'list@host.com',
          displayName: '',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual([]);
  });

  it('should keep an outgoing message to a named contact even when its subject is unsubscribe', () => {
    const messages = [
      buildMessage('human-recipient', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'user@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle: 'john@vendor.com',
          displayName: 'John Doe',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual(
      messages,
    );
  });

  it('should keep an incoming message that merely happens to be about unsubscribing', () => {
    const messages = [
      buildMessage(
        'human-asking-to-unsubscribe',
        [
          {
            role: MessageParticipantRole.FROM,
            handle: 'john@vendor.com',
            displayName: 'John',
          },
          {
            role: MessageParticipantRole.TO,
            handle: 'user@example.com',
            displayName: 'User',
          },
        ],
        MessageDirection.INCOMING,
      ),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual(
      messages,
    );
  });

  it('should keep a message that also reaches a human recipient', () => {
    const messages = [
      buildMessage('mixed-recipients', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'user@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle: 'unsubscribe@mail.vendor.com',
          displayName: 'Vendor',
        },
        {
          role: MessageParticipantRole.CC,
          handle: 'john@vendor.com',
          displayName: 'John',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual(
      messages,
    );
  });

  it('should keep a message the user only sent to their own handles', () => {
    const messages = [
      buildMessage('self-sent', [
        {
          role: MessageParticipantRole.FROM,
          handle: 'USER@example.com',
          displayName: 'User',
        },
        {
          role: MessageParticipantRole.TO,
          handle: 'user@example.com',
          displayName: 'User',
        },
      ]),
    ];

    expect(filterOutUnsubscribeRequests(OWN_HANDLES, messages)).toEqual(
      messages,
    );
  });
});
